[package]
edition = "2021"
name = "farmfe_plugin_dsv"
version = "0.0.1"
authors = ["CCherry07 <c_chenjunguang@163.com>"]
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
farmfe_core = { version = "0.6.2" }
farmfe_toolkit_plugin_types = { version = "0.0.18" }
farmfe_macro_plugin = { version = "0.0.4" }
csv = "1.3.0"
serde = "1.0.197"
serde_json = "1.0.116"
farmfe_toolkit = "0.0.11"
