[package]
edition = "2021"
name = "farm_plugin_dsv"
version = "0.0.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
farmfe_core = { version = "*" }
farmfe_toolkit_plugin_types = { version = "*" }
farmfe_macro_plugin = { version = "*" }
csv = "1.3.0"
serde = "1.0.197"
serde_json = "1.0.116"
farmfe_toolkit = "0.0.7"
