[package]
edition = "2021"
name = "farmfe_plugin_virtual"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
farmfe_core = { version = "0.6.2" }
farmfe_toolkit_plugin_types = { version = "0.0.18" }
farmfe_macro_plugin = { version = "0.0.4" }
