[package]
edition = "2021"
name = "farmfe_plugin_react_components"
version = "0.0.1"
authors = ["CCherry07 <c_chenjunguang@163.com>"]
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
farmfe_core = { version = "0.6.2" }
farmfe_utils = { version = "0.1.5" }
farmfe_toolkit_plugin_types = { version = "0.0.18" }
farmfe_macro_plugin = { version = "0.0.4" }
serde = { version = "1.0.197", features = ["derive"] }
farmfe_toolkit = "0.0.11"
glob = "0.3.1"
walkdir = "2.5.0"
openssl = "0.10.64"
