[package]
edition = "2021"
name = "farmfe_plugin_react_components"
version = "0.0.1"
authors = ["CCherry07 <c_chenjunguang@163.com>"]
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
farmfe_core = { version = "*" }
farmfe_utils = { version = "*" }
farmfe_toolkit_plugin_types = { version = "*" }
farmfe_macro_plugin = { version = "*" }
serde = { version = "1.0.197", features = ["derive"] }
farmfe_toolkit = "0.0.8"
glob = "0.3.1"
walkdir = "2.5.0"
