[package]
edition = "2021"
name = "farmfe_plugin_icons"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
farmfe_core = { version = "0.6.2" }
farmfe_toolkit_plugin_types = { version = "0.0.18" }
farmfe_macro_plugin = { version = "0.0.4" }
farmfe_toolkit = "0.0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
farmfe_utils = "0.1.4"
svgr-rs = "0.1.2"
once_cell = "1.19.0"
fervid = "0.2.0"
reqwest = "0.12.5"
tokio = { version = "1.38.0", features = ["full"] }
walkdir = "2.5.0"
xmltree = "0.10.3"
# rand = "0.8"
