name: Publish packages and crates
on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  call-rust-build:
    uses: ./.github/workflows/build.yaml

  release:
    name: Release
    needs: [call-rust-build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      # batch download artifacts
      - uses: actions/download-artifact@v3
        with:
          path: /tmp/artifacts
      - name: Move Artifacts
        run: |
          for abi in linux-x64-gnu linux-x64-musl darwin-x64 win32-x64-msvc linux-arm64-musl linux-arm64-gnu darwin-arm64 win32-ia32-msvc win32-arm64-msvc
          do
             for package in dsv react-components virtual yaml strip image url icons
              do
                if [ -z "$(ls -A /tmp/artifacts/${{github.sha}}-${abi}-${package})" ]; then
                  echo "Folder is empty"
                  echo "::set-output name=isEmpty::true"
                else
                  echo "Folder is not empty"
                  mv /tmp/artifacts/${{ github.sha }}-${abi}-${package}/* ./packages/${package}/npm/${abi}
                fi
              done
          done

      - name: Install Dependencies
        run: npm install -g pnpm@9.1.0 && pnpm i --frozen-lockfile

      - name: Publish to npm
        run: npm set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} && npm config set access public && pnpm --filter "[HEAD^]" publish --no-git-checks
